# -*- coding: utf-8 -*-
"""26.05.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19ZtFBoEfqEPcSzCjWt5hocSjYUFYZgRF
"""

print ("Привет мир")