# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ce8xBKPO8gSULWvIlDrEAa9trYKq2bcW
"""

import sqlite3
#Создание таблицы Студенты
connection = sqlite3.connect('teacher.db')
cursor = connection.cursor()
query = """CREATE TABLE Students(
Student_Id INTEGER,
Student_Name TEXT,
School_Id INTEGER PRIMARY KEY);"""
cursor.execute(query)
connection.commit()
connection.close()

import sqlite3
#Заполнение таблицы Студенты
connection = sqlite3.connect('teacher.db')
cursor = connection.cursor()
query = """INSERT INTO Students(Student_Id, Student_Name, School_Id)
VALUES
(201, 'Иван', 1),
(202, 'Петр', 2),
(203, 'Анастасия', 3),
(204, 'Игорь', 4);"""
cursor.execute(query)
connection.commit()
connection.close()

import sqlite3

# Создание второй таблицы
connection = sqlite3.connect('teacher.db')
cursor = connection.cursor()
query = """CREATE TABLE School (
School_Id INTEGER NOT NULL PRIMARY KEY,
School_Name TEXT NOT NULL,
Place_Count INTEGER NOT NULL);"""
cursor.execute(query)
connection.commit()
connection.close()

import sqlite3

# Наполнение второй табл
connection = sqlite3.connect('teacher.db')
cursor = connection.cursor()
query = """INSERT INTO School (School_Id , School_Name , Place_Count)
VALUES
('1', 'Протон', 200),
('2', 'Преспектива', 300),
('3', 'Спектр', 400),
('4', 'Содружество', 500);"""
cursor.execute(query)
connection.commit()
connection.close()

# import sqlite3
# def get_school(school_id):
#   connection = sqlite3.connect("teacher.db")
#   cursor = connection.cursor()
#   query = """SELECT * FROM School WHERE School_Id = ?"""
#   cursor.execute(query,(school_id,))
#   rec = cursor.fetchall()
#   connection.close()
#   return rec[1]


# def get_stud(student_id):
#   connection = sqlite3.connect('teacher.db')
#   cursor = connection.cursor()

#   query = """SELECT * FROM Students WHERE Student_Id = ?"""
#   cursor.execute(query,(student_id,))
#   rec = cursor.fetchall()
#   for raw in rec:
#     print('Id Студента', raw[0])
#     print('Имя Студента', raw[1])
#     print('Id Школы', raw[2])
#     print('Название Школы', get_school(raw[2]))
#   connection.close()
# n = input('Номер студента от 201 до 204 - ')

# get_stud(n)

import sqlite3
def get_stud(student_id):
  con = sqlite3.connect('teacher.db')
  cur = con.cursor()
  query = """SELECT Students.Student_Id, Students.Student_Name, School.School_Id, School.School_Name FROM School JOIN Students ON School.School_Id = Students.School_Id WHERE Students.Student_Id = ?"""
  cur.execute(query,(student_id,))
  rec = cur.fetchall()
  print(rec)

get_stud(202)